# server配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /admin

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: admin

# 连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zzs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# 日志记录
logging:
  config: classpath:logback.xml