# server配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /admin

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: admin

  # 连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.111:3306/zhuzs?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://127.0.0.1:3306/zhuzs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Root1234@

  # redis
  redis:
    #redis服务器地址
    host: localhost
    port: 6379
    password:
    database: 1
    #redis连接超时时间（毫秒）
    timeout: 18000
    #lettuce连接池配置 springboot2.x后默认使用Lettuce:
    #lettuce:
    jedis:
      pool:
        # 连接池最小空闲连接
        min-idle: 1
        # 连接池最大空闲连接
        max-idle: 5
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大空闲连接（使用负值表示没有限制）
        max-wait: -1

# MyBatisPlus 配置
mybatis-plus:
  # 映射文件所在路径
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhuzs.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# nacos 配置
nacos:
  config:
    server-addr: 127.0.0.1:8848
# swagger ui
swagger:
  enabled: true


# 日志记录
logging:
  config: classpath:logback.xml

########################################################################################################################

# 校验用户基本信息
user:
  orgNo: test001
